# Workflow to create a draft release whenever a tag is pushed to main
# A lot of inspiration/techniques from: https://github.com/courselore/courselore/blob/c0b541d63fc656986ebeab4af3f3dc9bc2909972/.github/workflows/main.yml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build Release

jobs:
  insiders-build:
    strategy:
      matrix:
        os: [windows, ubuntu]
        include:
          - os: windows
            build: npx caxa -i . -o "fa-gallery-downloader-${{github.ref_name}}.exe" -m "Unpackaging, please wait..." -e "./.**" "fa_gallery_downloader" "build" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/index.js"
            artifact: fa-gallery-downloader-${{github.ref_name}}.exe
          - os: ubuntu
            build: |
              npx caxa -i . -o "fa-gallery-downloader-${{github.ref_name}}" -m "Unpackaging, please wait..." -e "./.**" "fa_gallery_downloader" "build" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/index.js"
              tar -czf "fa-gallery-downloader-${{github.ref_name}}.tgz" "fa-gallery-downloader-${{github.ref_name}}"
            artifact: fa-gallery-downloader-${{github.ref_name}}.tgz
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.20.0
      - run: npm ci
      - run: ${{matrix.build}}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.artifact}}
          path: ${{matrix.artifact}}
  create-draft-release:
    needs: [insiders-build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: fa-gallery-downloader-${{github.ref_name}}.exe
      - uses: actions/download-artifact@v2
        with:
          name: fa-gallery-downloader-${{github.ref_name}}.tgz
      - uses: actions/create-release@v1
        name: create-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref_name}}
          release_name: ${{github.ref_name}}
          draft: true
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create-release.outputs.upload_url}}
          asset_path: fa-gallery-downloader-${{github.ref_name}}.exe
          asset_name: fa-gallery-downloader-${{github.ref_name}}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create-release.outputs.upload_url}}
          asset_path: fa-gallery-downloader-${{github.ref_name}}.tgz
          asset_name: fa-gallery-downloader-${{github.ref_name}}.tgz
          asset_content_type: application/gzip
